;; Generated by Gemini 3.5 Flash

(module
  ;; Import the output character function
  (import "walc" "output" (func $output (param i32)))

  ;; Helper: Prints 'Y' (89) if condition is true (non-zero), 'N' (78) if false (0)
  (func $assert (param $cond i32)
    (if (local.get $cond)
      (then (call $output (i32.const 89)))  ;; 'Y'
      (else (call $output (i32.const 78)))  ;; 'N'
    )
  )

  (func (export "main")
    ;; ==========================================
    ;; 1. i32.div_u (Unsigned 32-bit Division)
    ;; ==========================================

    ;; Basic division: 6 / 2 == 3
    (call $assert (i32.eq (i32.const 3) (i32.div_u (i32.const 6) (i32.const 2))))

    ;; Division with truncation: 7 / 2 == 3
    (call $assert (i32.eq (i32.const 3) (i32.div_u (i32.const 7) (i32.const 2))))

    ;; Division by 1: 5 / 1 == 5
    (call $assert (i32.eq (i32.const 5) (i32.div_u (i32.const 5) (i32.const 1))))

    ;; Zero dividend: 0 / 5 == 0
    (call $assert (i32.eq (i32.const 0) (i32.div_u (i32.const 0) (i32.const 5))))

    ;; Large unsigned values: 0xFFFFFFFF / 2 == 0x7FFFFFFF
    (call $assert (i32.eq (i32.const 0x7FFFFFFF) (i32.div_u (i32.const 0xFFFFFFFF) (i32.const 2))))


    ;; ==========================================
    ;; 2. i32.div_s (Signed 32-bit Division)
    ;; ==========================================

    ;; Pos / Pos: 6 / 2 == 3
    (call $assert (i32.eq (i32.const 3) (i32.div_s (i32.const 6) (i32.const 2))))

    ;; Neg / Pos: -6 / 2 == -3
    (call $assert (i32.eq (i32.const -3) (i32.div_s (i32.const -6) (i32.const 2))))

    ;; Pos / Neg: 6 / -2 == -3
    (call $assert (i32.eq (i32.const -3) (i32.div_s (i32.const 6) (i32.const -2))))

    ;; Neg / Neg: -6 / -2 == 3
    (call $assert (i32.eq (i32.const 3) (i32.div_s (i32.const -6) (i32.const -2))))

    ;; Truncation towards zero (negative): -5 / 2 == -2
    (call $assert (i32.eq (i32.const -2) (i32.div_s (i32.const -5) (i32.const 2))))

    ;; Truncation towards zero (negative): 5 / -2 == -2
    (call $assert (i32.eq (i32.const -2) (i32.div_s (i32.const 5) (i32.const -2))))


    ;; ==========================================
    ;; 3. i64.div_u (Unsigned 64-bit Division)
    ;; ==========================================

    ;; Basic division: 12 / 3 == 4
    (call $assert (i64.eq (i64.const 4) (i64.div_u (i64.const 12) (i64.const 3))))

    ;; Division with truncation: 14 / 3 == 4
    (call $assert (i64.eq (i64.const 4) (i64.div_u (i64.const 14) (i64.const 3))))

    ;; Large unsigned 64-bit values: 0xFFFFFFFFFFFFFFFF / 2 == 0x7FFFFFFFFFFFFFFF
    (call $assert (i64.eq (i64.const 0x7FFFFFFFFFFFFFFF) (i64.div_u (i64.const 0xFFFFFFFFFFFFFFFF) (i64.const 2))))


    ;; ==========================================
    ;; 4. i64.div_s (Signed 64-bit Division)
    ;; ==========================================

    ;; Pos / Neg: 12 / -3 == -4
    (call $assert (i64.eq (i64.const -4) (i64.div_s (i64.const 12) (i64.const -3))))

    ;; Neg / Neg: -12 / -3 == 4
    (call $assert (i64.eq (i64.const 4) (i64.div_s (i64.const -12) (i64.const -3))))

    ;; Truncation towards zero: -13 / 3 == -4
    (call $assert (i64.eq (i64.const -4) (i64.div_s (i64.const -13) (i64.const 3))))


    ;; ==========================================
    ;; 5. Overflow Limit Assertions (Valid Bounds)
    ;; ==========================================

    ;; i32: Max negative value divided by -1 overflows in signed math, but (-2147483648 / 1) is valid
    (call $assert (i32.eq (i32.const -2147483648) (i32.div_s (i32.const -2147483648) (i32.const 1))))

    ;; i64: Max negative value divided by 1 is valid
    (call $assert (i64.eq (i64.const -9223372036854775808) (i64.div_s (i64.const -9223372036854775808) (i64.const 1))))


    ;; ==========================================
    ;; Conclusion
    ;; ==========================================

    ;; Print "OK"
    (call $output (i32.const 79)) ;; 'O'
    (call $output (i32.const 75)) ;; 'K'
  )
)
