;; Generated by Google Gemini 3.5 Flash

(module
  ;; Import the output character function
  (import "walc" "output" (func $output (param i32)))

  ;; Define memory with an initial size of 1 page and no maximum limit
  (memory 1)

  ;; Helper: Prints 'Y' (89) if condition is true (non-zero), 'N' (78) if false (0)
  (func $assert (param $cond i32)
    (if (local.get $cond)
      (then (call $output (i32.const 89)))  ;; 'Y'
      (else (call $output (i32.const 78)))  ;; 'N'
    )
  )

  (func (export "main")
    ;; ==========================================
    ;; 1. Initial State Check
    ;; ==========================================

    ;; Initial memory size must be exactly 1 page
    (call $assert (i32.eq (i32.const 1) (memory.size)))


    ;; ==========================================
    ;; 2. Continuous Unbounded Expansion
    ;; ==========================================

    ;; Grow by 1 page. Returns previous size (1)
    (call $assert (i32.eq (i32.const 1) (memory.grow (i32.const 1))))
    (call $assert (i32.eq (i32.const 2) (memory.size)))

    ;; Grow by 0 pages. Returns previous size (2)
    (call $assert (i32.eq (i32.const 2) (memory.grow (i32.const 0))))
    (call $assert (i32.eq (i32.const 2) (memory.size)))

    ;; Grow by 3 pages at once. Returns previous size (2), new size should be 5
    (call $assert (i32.eq (i32.const 2) (memory.grow (i32.const 3))))
    (call $assert (i32.eq (i32.const 5) (memory.size)))

    ;; Grow by 5 pages at once. Returns previous size (5), new size should be 10
    (call $assert (i32.eq (i32.const 5) (memory.grow (i32.const 5))))
    (call $assert (i32.eq (i32.const 10) (memory.size)))


    ;; ==========================================
    ;; 3. Massive Valid Growth Step
    ;; ==========================================

    ;; Grow by a larger chunk (e.g., 50 pages).
    ;; Without a max limit, this should successfully return 10.
    (call $assert (i32.eq (i32.const 10) (memory.grow (i32.const 50))))

    ;; New size must be exactly 60 pages
    (call $assert (i32.eq (i32.const 60) (memory.size)))


    ;; ==========================================
    ;; Conclusion
    ;; ==========================================

    ;; Print "OK"
    (call $output (i32.const 79)) ;; 'O'
    (call $output (i32.const 75)) ;; 'K'
  )
)
