#!/usr/bin/env bash

HELP=\
'Usage:
$ textstat INPUT.walc

Counts the number of abstraction, application, and variable terms
in a lambda expression.

Example:
    $ echo "[f ([x (f (x x))] [x (f (x x))])]" > /tmp/example.walc
    $ textstat /tmp/example.walc
Output:
    Number of abstraction terms: 3
    Number of application terms: 5
    Number of variable terms: 6'

if [ "$1" = "" -o "$1" = "--help" ]
then
    echo "$HELP"
    exit 0
fi

if [ "$1" != "-" -a ! -f "$1" ]
then
    echo "Error: file '$1' not found"
    exit 1
fi

echo -n "Number of abstraction terms: "
cat $1 | grep -oE '\[' | wc -l
echo -n "Number of application terms: "
cat $1 | grep -oE '\(' | wc -l
echo -n "Number of variable terms: "
cat $1 | grep -oE '(^|[^\[])\b[a-zA-Z0-9_]+' | wc -l
echo -n "Number of all terms: "
cat $1 | grep -oE '\(|\b[a-zA-Z0-9_]+' | wc -l
