#!/usr/bin/env bash

# Converts lambda expressions from the WALC text format (with brackets)
# to the traditional mathematical notation (with λ and parentheses).
#
# Usage:
# $ cat INPUT.walc | text2math
#
# Example:
# $ echo "[f ([x (f (x x))] [x (f (x x))])]" | text2math
# Output:
#   (λf. ((λx. (f (x x))) (λx. (f (x x)))))

sed -r 's/\[([_0-9a-zA-Z]+)/(λ\1./g ; s/]/)/g'
