// Generated by Google Gemini 3.5 Flash and then edited to fix printing.
// Minimax search depth was reduced to 3, otherwise it's far too slow :(.

#![no_std]
#![no_main]
mod walc;
use walc::*;

#[derive(Copy, Clone, PartialEq, Debug)]
enum Player {
    None,
    X, // User
    O, // AI
}

struct Game {
    board: [[Player; 3]; 3],
}

impl Game {
    fn new() -> Self {
        Self {
            board: [[Player::None; 3]; 3],
        }
    }

    fn print_board(&self) {
        print_string("    0   1   2  \n");

        for r in 0..3 {
            print_string("  +---+---+---+\n");

            print_byte(b'0' + r as u8);
            print_byte(b' ');

            for c in 0..3 {
                print_string("|");
                print_string(match self.board[r][c] {
                    Player::None => "   ",
                    Player::X => " X ",
                    Player::O => " O ",
                });
            }
            print_string("|\n");
        }

        print_string("  +---+---+---+\n");
    }

    fn check_winner(&self) -> Player {
        // Rows and Columns
        for i in 0..3 {
            if self.board[i][0] != Player::None
                && self.board[i][0] == self.board[i][1]
                && self.board[i][1] == self.board[i][2]
            {
                return self.board[i][0];
            }
            if self.board[0][i] != Player::None
                && self.board[0][i] == self.board[1][i]
                && self.board[1][i] == self.board[2][i]
            {
                return self.board[0][i];
            }
        }
        // Diagonals
        if self.board[0][0] != Player::None
            && self.board[0][0] == self.board[1][1]
            && self.board[1][1] == self.board[2][2]
        {
            return self.board[0][0];
        }
        if self.board[0][2] != Player::None
            && self.board[0][2] == self.board[1][1]
            && self.board[1][1] == self.board[2][0]
        {
            return self.board[0][2];
        }

        Player::None
    }

    fn is_full(&self) -> bool {
        self.board
            .iter()
            .all(|row| row.iter().all(|&c| c != Player::None))
    }

    fn minimax(&mut self, depth: i32, max_depth: i32, is_maximizing: bool) -> i32 {
        let winner = self.check_winner();
        if winner == Player::O {
            return 10 - depth;
        }
        if winner == Player::X {
            return depth - 10;
        }
        if self.is_full() || depth >= max_depth {
            return 0;
        }

        if is_maximizing {
            let mut best_score = i32::MIN;
            for r in 0..3 {
                for c in 0..3 {
                    if self.board[r][c] == Player::None {
                        self.board[r][c] = Player::O;
                        let score = self.minimax(depth + 1, max_depth, false);
                        self.board[r][c] = Player::None;
                        best_score = best_score.max(score);
                    }
                }
            }
            best_score
        } else {
            let mut best_score = i32::MAX;
            for r in 0..3 {
                for c in 0..3 {
                    if self.board[r][c] == Player::None {
                        self.board[r][c] = Player::X;
                        let score = self.minimax(depth + 1, max_depth, true);
                        self.board[r][c] = Player::None;
                        best_score = best_score.min(score);
                    }
                }
            }
            best_score
        }
    }

    fn ai_move(&mut self) {
        let mut best_score = i32::MIN;
        let mut best_move = (0, 0);
        let max_depth = 3;

        for r in 0..3 {
            for c in 0..3 {
                if self.board[r][c] == Player::None {
                    self.board[r][c] = Player::O;
                    let score = self.minimax(0, max_depth, false);
                    self.board[r][c] = Player::None;
                    if score > best_score {
                        best_score = score;
                        best_move = (r, c);
                    }
                }
            }
        }
        self.board[best_move.0][best_move.1] = Player::O;
    }
}

fn main() {
    let mut game = Game::new();

    print_string("Welcome to Tic-Tac-Toe! (^o^)/\n");

    game.print_board();

    loop {
        // User turn
        loop {
            print_string("Your move (row column): ");
            let input = read_line();
            let coords: Vec<&str> = input.split_whitespace().collect();

            if coords.len() == 2 {
                if let (Ok(r), Ok(c)) = (coords[0].parse::<usize>(), coords[1].parse::<usize>()) {
                    if r < 3 && c < 3 && game.board[r][c] == Player::None {
                        game.board[r][c] = Player::X;
                        break;
                    }
                }
            }
            print_string("Invalid move. Try again. :-/\n");
        }

        game.print_board();

        if game.check_winner() == Player::X {
            print_string("You win! :-D\n");
            break;
        }
        if game.is_full() {
            print_string("It's a draw! :-O\n");
            break;
        }

        // AI turn
        print_string("My move... :-P\n");
        game.ai_move();
        game.print_board();

        if game.check_winner() == Player::O {
            print_string("I win! ;-)\n");
            break;
        }
        if game.is_full() {
            print_string("It's a draw! :-O\n");
            break;
        }
    }
}
